name = "ForgePackBase"
author = "Den4enko"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "758cd5de20848dd88a0ba601103e31885cf79635a13de316ed19bc70daf05f6a"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
