name = "ForgePackBase"
author = "Den4enko"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17524abe43a667ee65461c1e661beace9aaf75f709736aa853200a012e8e8a11"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
